# Generated by Django 4.1 on 2022-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysite',
            options={'ordering': ['-title'], 'verbose_name': 'My work', 'verbose_name_plural': 'My works'},
        ),
        migrations.RemoveField(
            model_name='mysite',
            name='photo',
        ),
        migrations.AddField(
            model_name='mysite',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание письма'),
        ),
        migrations.AddField(
            model_name='mysite',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
    ]
